### ISSUE TITLE
Menu SubItems should be filtered based on user group

### ISSUE THREAD

**Issue by bowserm** [mjbvis/CMS#2]
Menu SubItems should be entirely database driven. This means that the database should store all of the necessary information to determine which groups should be able to see which tabs. For example, a parent should not be able to enroll a new student. Thus, they shouldn't see that tab.

1) The database schema needs to be updated to handle this.
2) The models need to be mapped in the application
3) The menu_helper needs to be refactored to provide this functionality

**Comment by fieldju** [comment]
this is not a real issue
