### ISSUE TITLE
Get rid of WaitlistForm sub menuitem

### ISSUE THREAD

**Issue by bowserm** [mjbvis/CMS#34]
Having both the "Waitlist Student" and "Register New Student" tabs under the Admissions menuitem is confusing. Get rid of the "Waitlist Student" sub item and put a link to the WaitlistForm inside of the "Register New Student" page.

**Comment by fieldju** [comment]
I modified the lay out and menu system for the admissions process and no longer feel that this is an issue or should be done. Therefore I am going to close this issue and we can re-open it later if it is decided that it is still an issue.
