### ISSUE TITLE
Add New Parent User

### ISSUE THREAD

**Issue by bowserm** [mjbvis/CMS#7]
New Parent User should be in the Parent group

An email should be sent to the new user with an auto-generated password.
Usernames should be validated. Do not allow duplicate usernames.

The following data needs to be inserted into the parent table after the user is created:
Parent table:
    -first name
    -middle name (optional)
    -last name
    -user id
    -email
    -Employer (optional)
    -Occupation (optional)
    -IsDepositPaid (defaulted to false. don't ask for this on the form)
    -IsProspect (default to true. don't ask for this on the form)

**Comment by fieldju** [comment]
done
